{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-core/4.1.1-ohos-2.2.21-2/koin-core-4.1.1-ohos-2.2.21-2.module",
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "4.1.1-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-iosSimulatorArm64Main-4.1.1-ohos-2.2.21-2.klib",
          "url": "koin-core-iossimulatorarm64-4.1.1-ohos-2.2.21-2.klib",
          "size": 235409,
          "sha512": "eaf8373152537aa4f032eb55ed5e19e1f566111aab3090a48fb318ebee43cdc5dfb560e1c06c97519ac370e4d2ac6d5a58e981fa04d02536f3ef6658dea45426",
          "sha256": "ed08c700509fce4a557d2aaebc2f47ffd1af6568c23e292d26bc3311870b7f6c",
          "sha1": "97b602bd51b8036fcace7fd4353d8c1040565eb0",
          "md5": "15fa7912b3bffc5d86c8874b167815c0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "koin-core-iossimulatorarm64-4.1.1-ohos-2.2.21-2-sources.jar",
          "url": "koin-core-iossimulatorarm64-4.1.1-ohos-2.2.21-2-sources.jar",
          "size": 74792,
          "sha512": "1974a14f0d31e888823f515f72df923f77d3e4d0ff225cf4184a742566f1656fa16595b485ac630458598ae3db58481ec0f95f31a9073902f71e2c09680cb251",
          "sha256": "f2527da980ebf12caaf7e4925846e3866574c902f0c37fa55dfccb287454124c",
          "sha1": "b9b6ae39d595d0612ee3e5d77b469d94b2411c12",
          "md5": "1db2c17423c59148134f1bca48e78df7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-iossimulatorarm64-4.1.1-ohos-2.2.21-2-metadata.jar",
          "url": "koin-core-iossimulatorarm64-4.1.1-ohos-2.2.21-2-metadata.jar",
          "size": 261,
          "sha512": "564af966012a64650dfab3682250004a98b9937cc9ea16c9196ff57e796e8b23cd767b6915892571a5db337fe5249def1258fbb0f7417215f76e2c309869fd1f",
          "sha256": "66b0350b221a38861b1ce66fea4fa390fa5c14d6e2757b01654a978cd6f9a3f2",
          "sha1": "f95d862e7daae5e34f1989a96992cc97919d2d94",
          "md5": "773cce04fc39e0c043f3fe2316cb6372"
        }
      ]
    }
  ]
}
