{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-core/4.1.1-ohos-2.2.21-2/koin-core-4.1.1-ohos-2.2.21-2.module",
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "4.1.1-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-iosArm64Main-4.1.1-ohos-2.2.21-2.klib",
          "url": "koin-core-iosarm64-4.1.1-ohos-2.2.21-2.klib",
          "size": 235344,
          "sha512": "2390dc0de50d2ac7268d244ef6edff000c33e27fa3f72039b306726a761272008de2963c55aa527e750bf11cc4876c7f0c33e336b162d1e3f9b14c775b9eca4b",
          "sha256": "e53ced3a96711c824a1a9a0a671732e6d154b2a3c7a7009e4dd10c2e003f0209",
          "sha1": "a841f666667f4c956f098bd0d1973092b368cbf2",
          "md5": "4db660e19e8103b675ab897032009f24"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "koin-core-iosarm64-4.1.1-ohos-2.2.21-2-sources.jar",
          "url": "koin-core-iosarm64-4.1.1-ohos-2.2.21-2-sources.jar",
          "size": 74792,
          "sha512": "1974a14f0d31e888823f515f72df923f77d3e4d0ff225cf4184a742566f1656fa16595b485ac630458598ae3db58481ec0f95f31a9073902f71e2c09680cb251",
          "sha256": "f2527da980ebf12caaf7e4925846e3866574c902f0c37fa55dfccb287454124c",
          "sha1": "b9b6ae39d595d0612ee3e5d77b469d94b2411c12",
          "md5": "1db2c17423c59148134f1bca48e78df7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-iosarm64-4.1.1-ohos-2.2.21-2-metadata.jar",
          "url": "koin-core-iosarm64-4.1.1-ohos-2.2.21-2-metadata.jar",
          "size": 261,
          "sha512": "564af966012a64650dfab3682250004a98b9937cc9ea16c9196ff57e796e8b23cd767b6915892571a5db337fe5249def1258fbb0f7417215f76e2c309869fd1f",
          "sha256": "66b0350b221a38861b1ce66fea4fa390fa5c14d6e2757b01654a978cd6f9a3f2",
          "sha1": "f95d862e7daae5e34f1989a96992cc97919d2d94",
          "md5": "773cce04fc39e0c043f3fe2316cb6372"
        }
      ]
    }
  ]
}
