{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-core/4.1.1-ohos-2.2.21-2/koin-core-4.1.1-ohos-2.2.21-2.module",
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "4.1.1-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-jvm-4.1.1-ohos-2.2.21-2.jar",
          "url": "koin-core-jvm-4.1.1-ohos-2.2.21-2.jar",
          "size": 408012,
          "sha512": "ecc5ce1f010122eb9ee925bfd07a76731387bf47c9082834af48d62881fa6e9c61e392d682a4cc73a4cc57738a2952d25e5206af4fd72125b3b3292b4eb3a7ff",
          "sha256": "1375f8f101a88bb8a30ca2feea77e7a904bcb0ad3415a2eaa378189c29c89dc0",
          "sha1": "c74688738289c531f63b793194b327242efef344",
          "md5": "66d016bba7decd5d3b7423d53a4702e8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-jvm-4.1.1-ohos-2.2.21-2.jar",
          "url": "koin-core-jvm-4.1.1-ohos-2.2.21-2.jar",
          "size": 408012,
          "sha512": "ecc5ce1f010122eb9ee925bfd07a76731387bf47c9082834af48d62881fa6e9c61e392d682a4cc73a4cc57738a2952d25e5206af4fd72125b3b3292b4eb3a7ff",
          "sha256": "1375f8f101a88bb8a30ca2feea77e7a904bcb0ad3415a2eaa378189c29c89dc0",
          "sha1": "c74688738289c531f63b793194b327242efef344",
          "md5": "66d016bba7decd5d3b7423d53a4702e8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koin-core-jvm-4.1.1-ohos-2.2.21-2-sources.jar",
          "url": "koin-core-jvm-4.1.1-ohos-2.2.21-2-sources.jar",
          "size": 77125,
          "sha512": "bc20fd40d9758fcd6b05d4edc49e179c609b4dc10a6923ebbfbead2782e48caac86039770cc117e5c373c877222d472fa94ca0e5da9b7f7751174b4c3523d155",
          "sha256": "40bca314b202aedf28fc343b9f9f758f954b1777cb1d671d25de5e2a41271371",
          "sha1": "c216a010bb4af1332c1ca93804289ca14e72d9d5",
          "md5": "e402c62a1d068e6196009648a01b8d22"
        }
      ]
    }
  ]
}
