{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-core/4.1.1-ohos-2.2.21-2/koin-core-4.1.1-ohos-2.2.21-2.module",
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "4.1.1-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-iosX64Main-4.1.1-ohos-2.2.21-2.klib",
          "url": "koin-core-iosx64-4.1.1-ohos-2.2.21-2.klib",
          "size": 235331,
          "sha512": "666dc093633b836ba9faedd29ab419ebb68b1a80ee19d5a5153c689eb378e284211bd136af37ae077847dd9e1930a0cb39c6928013bae54096222862642ae12f",
          "sha256": "4f0b62cc005b8a212384da4c35134168663ae47c5b0457b5cf92bef7e447bcbf",
          "sha1": "7528127488579718d59ee18cde0842d4340ba2a2",
          "md5": "873441b6581925d069a3a26e99bb1a05"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "koin-core-iosx64-4.1.1-ohos-2.2.21-2-sources.jar",
          "url": "koin-core-iosx64-4.1.1-ohos-2.2.21-2-sources.jar",
          "size": 74792,
          "sha512": "1974a14f0d31e888823f515f72df923f77d3e4d0ff225cf4184a742566f1656fa16595b485ac630458598ae3db58481ec0f95f31a9073902f71e2c09680cb251",
          "sha256": "f2527da980ebf12caaf7e4925846e3866574c902f0c37fa55dfccb287454124c",
          "sha1": "b9b6ae39d595d0612ee3e5d77b469d94b2411c12",
          "md5": "1db2c17423c59148134f1bca48e78df7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-iosx64-4.1.1-ohos-2.2.21-2-metadata.jar",
          "url": "koin-core-iosx64-4.1.1-ohos-2.2.21-2-metadata.jar",
          "size": 261,
          "sha512": "bab3cd72cac34d11c58019399adae59d32a1dcea4d0ed2bdce39069749f5fe0ab47c52254dd1674635e26f0ef8091476b1a2019b61811b3829df776174680460",
          "sha256": "6ba7b70b1c5ec694f36381cd0bee69da6b707f6dcdf5e73559b607d4460af6d5",
          "sha1": "cc4bbd087fdf7158d231e6c52a6fe35168efe5a8",
          "md5": "3469fd0a3dd4aeadbf9cadb8e7a187b3"
        }
      ]
    }
  ]
}
